### PR TITLE
Add a nav feature

### PR DESCRIPTION
**Pull request by hileamlakB**
This feature allows the extension to make a nav bar on projects pages which
will make it easier  to navigate to different questions from different
parts of the page. This will be very handy as the number of projects
increase. Which is what seems to be happening

### CODE REVIEW

**Comment by hileamlakB** [comment]
You inspired automation in the group and I thought I would follow the trail. :)

**Comment by YourFavouriteOreo** [comment]
Oooh I like it ALOT. However, you forgot to support light mode :D . If we add features we shouldn't forget to support existing features.

**Comment by hileamlakB** [comment]
ok I forgot about the light mode I will quickly fix that

**Comment by hileamlakB** [comment]
so the color mode is fixed

**Comment by YourFavouriteOreo** [comment]
Merged on #2

**Pull request closed without merging**
